### PR TITLE
Maven central

### PR DESCRIPTION
**Pull request by Bixilon**
Seem to work: https://s01.oss.sonatype.org/content/repositories/releases/io/github/kotlin-graphics/kotlin-unsigned/3.3.32/

Also bumped gradle, removed windows and mac workflows (they have no purpose in that repository)

Still need to wait for a reply https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-92182, once that is done, imma mail you all the environment variables along with credentials and signing keys (I think maintainer or owner permission is needed; not sure)

See https://github.com/kotlin-graphics/glm/issues/35

### CODE REVIEW

**Comment by elect86** [comment]
Thanks, I missed this one

**Comment by elect86** [comment]
So, I'm finally trying to publish on Central, but I get

> * What went wrong:
Execution failed for task ':publishMavenCentralPublicationToMavenCentralRepository'.
> Failed to publish publication 'maven' to repository 'mavenCentral'
   > Artifact unsigned-jvm-3.4.0.jar wasn't produced by this build.

Any idea what's the problem?

**Comment by Bixilon** [comment]
Probably because you did not put the signing key/nexus credentials as environment variables (same problem in glm)

Should I publish it? Normally github should automatically publish it (if the secret is there)

**Comment by elect86** [comment]
So, as far as I got it, whenever you apply `maven-publish` to a Kotlin Multi Platform project, you get automatically all the needed publications already set up: the root `KotlinMultiplatform` and the platforms specific ones, in our case, `Jvm` and `Native`

Then you shall be able to publish all of them via `publishAllPublicationsTo`.

I modify the publication script in this way:

```
    publications {
        withType<MavenPublication> {
            groupId = "io.github.kotlin-graphics"
            artifactId = "kotlin-unsigned"
//            from(components["java"])
//            versionMapping {
//                usage("java-api") { fromResolutionOf("runtimeClasspath") }
//                usage("java-runtime") { fromResolutionResult() }
//            }
            pom {
                name = "kotlin-unsigned"
                description = "unsigned support for Kotlin via boxed types and unsigned operators"
                url = "https://github.com/kotlin-graphics/kotlin-unsigned"
                licenses { license { name = "MIT"; url = "https://choosealicense.com/licenses/mit/" } }
                developers {
                    developer { id = "elect86"; name = "Giuseppe Barbieri"; email = "elect86@gmail.com" }
                    developer { id = "bixilon"; name = "Moritz Zwerger"; email = "bixilon@bixilon.de" }
                }
                scm {
                    connection = "scm:git:https://github.com/kotlin-graphics/kotlin-unsigned.git"
                    developerConnection = "scm:git:ssh://git@github.com:kotlin-graphics/kotlin-unsigned.git"
                    url = "https://github.com/kotlin-graphics/kotlin-unsigned"
                }
            }
        }
    }
```

Since the publication are already there, we don't have to `create` anymore, that's why I'm using `withType` instead. 

Also I commented out the part about the java component and the versionMapping (it's possible to selectively apply them by `if(name=="jvm")`

Anyway, I now get this

> Execution failed for task ':publishJvmPublicationToMavenCentralRepository'.
> Failed to publish publication 'jvm' to repository 'mavenCentral'
   > Could not PUT 'https://s01.oss.sonatype.org/content/repositories/releases/io/github/kotlin-graphics/kotlin-unsigned/3.4.0/kotlin-unsigned-3.4.0.jar'. Received status code 401 from server: Unauthorized
   
All the credentials you sent me are in my home `.gradle.properties`, please feel free to try yourself, maybe I'm doing something wrong and I cant see it

**Comment by Bixilon** [comment]
`master` branch? I can check that later...

**Comment by elect86** [comment]
> `master` branch? I can check that later...

yep

**Pull request merged**
